### ISSUE TITLE
Adding a footer

### ISSUE THREAD

**Issue by rashen33** [Anandsg/House-booking#1]
A responsive footer is missing for this app.

**Comment by rashen33** [comment]
Hey @Anandsg Id like to add a responsive footer for this application. If you want me to work on it assign me. I'd like to help.

**Comment by Anandsg** [comment]
😅 Great @rashen33,  Actually this application isn't open source, I created it specifically for a company assignment you can check my NetflixGPT project for footer work

**Comment by rashen33** [comment]
Oops. Will do.
